The ``7-base_geometry`` module
=============================

Using ``BaseGeometry``
---------------------

Import the class:
    >>> BaseGeometry = __import__('7-base_geometry').BaseGeometry

Test instantiation:
    >>> bg = BaseGeometry()
    >>> type(bg)
    <class '7-base_geometry.BaseGeometry'>

Test area method:
    >>> bg.area()
    Traceback (most recent call last):
    Exception: area() is not implemented

Test integer validator with valid integers:
    >>> bg.integer_validator("my_int", 12)
    >>> bg.integer_validator("width", 89)

Test integer validator with string value:
    >>> bg.integer_validator("name", "John")
    Traceback (most recent call last):
    TypeError: name must be an integer

Test integer validator with zero:
    >>> bg.integer_validator("age", 0)
    Traceback (most recent call last):
    ValueError: age must be greater than 0

Test integer validator with negative value:
    >>> bg.integer_validator("distance", -4)
    Traceback (most recent call last):
    ValueError: distance must be greater than 0

Test integer validator with float:
    >>> bg.integer_validator("float", 3.14)
    Traceback (most recent call last):
    TypeError: float must be an integer

Test integer validator with bool:
    >>> bg.integer_validator("boolean", True)
    Traceback (most recent call last):
    TypeError: boolean must be an integer

Test integer validator with list:
    >>> bg.integer_validator("list", [1])
    Traceback (most recent call last):
    TypeError: list must be an integer

Test integer validator with None:
    >>> bg.integer_validator("none", None)
    Traceback (most recent call last):
    TypeError: none must be an integer

Test integer validator with tuple:
    >>> bg.integer_validator("tuple", (1,))
    Traceback (most recent call last):
    TypeError: tuple must be an integer

Test integer validator with set:
    >>> bg.integer_validator("set", {3, 4})
    Traceback (most recent call last):
    TypeError: set must be an integer

Test integer validator with missing arguments:
    >>> bg.integer_validator()
    Traceback (most recent call last):
    TypeError: integer_validator() missing 2 required positional arguments: 'name' and 'value'

Test integer validator with missing value:
    >>> bg.integer_validator("age")
    Traceback (most recent call last):
    TypeError: integer_validator() missing 1 required positional argument: 'value'

Test integer validator with extra arguments:
    >>> bg.integer_validator("age", 1, 2)
    Traceback (most recent call last):
    TypeError: integer_validator() takes 3 positional arguments but 4 were given
